# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://47.93.114.50:3306/hbw?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: PASSword123.